{% set name = "doepipeline" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/clicumu/doepipeline/archive/v{{ version }}.tar.gz
  sha256: 0fdc5595b422fb05c2c2c4ffcaa9b8c64f1df6807f832262c2bc4387dd0b1589

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [win]

requirements:
  host:
    - python >=3
    - pip

  run:
    - python >=3
    - pandas
    - pydoe2 >=1.2.0
    - pyyaml
    - statsmodels >=0.9.0
    - scipy >=1.2.1

test:
  imports:
    - doepipeline
    - doepipeline.executor

  commands: 
    - doepipeline --help

about:
  home: https://github.com/clicumu/doepipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Package for optimizing pipelines using DoE.

extra:
  recipe-maintainers:
    - druvus
